name: Code Linting

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Python linter
        id: pylint
        uses: docker://reasonsoftware/action-pylint:v2
